language: php

php:
  - hhvm

env:
  - SYMFONY_VERSION="2.3.*"

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

install:
  - sh travis_install_dependencies.sh

script:
  - phpunit --debug

notifications:
  email:
    on_success: always
    on_failure: always
